<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\CulinaryBlog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Database & Identity -->
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- JWT -->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.0" />
    <!-- Cache & Storage -->
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.0" />
    <PackageReference Include="Minio" Version="6.0.4" />
    <!-- Hangfire -->
    <PackageReference Include="Hangfire.Core" Version="1.8.18" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.18" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.10" />
  </ItemGroup>

</Project>
